const mongoose=require('mongoose');
const userSchema=new mongoose.Schema({
        name:{
            type:String,
            required:true
        },
        email:{
            type:String,
            required:true,
            unique:true
        },
        password:{
            type:String,
            required:true
        },
        phone_number:{
            type:String,
            required:false
        },
        pets_name:{
            type:String,
            required:false
        },
        location:{
            type:String,
            required:true
        }
    }); 
module.exports=mongoose.model('User',userSchema);